version: 2
project_name: tinypng-cli
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - main: main.go
    binary: tinypng
    env:
      - CGO_ENABLED=0
    targets:
      - linux_amd64
      - windows_amd64
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.Version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: ['zip']
checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256

changelog:
  sort: asc
  groups:
    - title: "New Features"
      regexp: "^feat:"
    - title: "Bug & Fixes"
      regexp: "^fix:"
    - title: "Changes"
      regexp: ".*"
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^code:'